// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	UserID      string `json:"user_id"`
	AccID       string `json:"acc_id"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	RoleName    string `json:"role_name"`
}
